---
- name: Transfer and execute a script.
  hosts: deployserver
  tasks:
    - name: Copy Artifact to Remote server
      copy:
        src: /tmp/spring/target/spring-petclinic-2.7.3.jar
        dest: /home/ubuntu/spring-petclinic/target
        # remote_src: yes

    - name: Copy and Execute the script
      script: /tmp/spring/deployJava.sh
