---
- name: Transfer and execute a script.
  hosts: deployserver
  tasks:
    - name: Copy Artifact to Remote server
      copy:
        remote_src: /home/ubuntu/spring-petclinic/target/*.jar
        dest: /root/spring-petclinic/target
    - name: Copy and Execute the script
      script: /root/spring-petclinic/deployJava.sh
