---
- name: Transfer and execute a script.
  hosts: deployserver
  tasks:
    - name: Copy Artifact to Remote server
      copy:
        src: /tmp/spring/target/spring-petclinic-2.7.3.jar
        dest: /home/ubuntu/spring-petclinic/target
        # remote_src: yes
    - name: Copy Artifact to Remote server
      copy:
        src: /tmp/spring/deployJava.sh
        dest: /home/ubuntu/spring-petclinic/
        # remote_src: yes
    - name: Node package manager
      npm:
        name: pm2
        global: yes

    - name: Execute the script
      command: /home/ubuntu/spring-petclinic/deployPm2.sh
